/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarketautomation;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Dhanush Pamujula
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Connection Con,aon;
    Statement St;
    ResultSet Rs;
    
    public Admin() {
        initComponents();
        this.setVisible(true);
        SelectManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void SelectManager()
    {
        try
    {
        Con =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","dhanu","root123");
        St= Con.createStatement();
        Rs = St.executeQuery("Select UserId,Name,Gender,Password from supermarket.Users where Role = 'MANAGER' order by name");
        ManagersTable.setModel(DbUtils.resultSetToTableModel(Rs));
        Con.close();
        
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ManagerId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        AddManager = new javax.swing.JButton();
        EditManager = new javax.swing.JButton();
        DeleteManager = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManagersTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN PAGE");

        jPanel1.setBackground(new java.awt.Color(0, 0, 180));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarketautomation/Shopping bag 1.jpg"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DMS MARKET");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setIconTextGap(5);

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MANAGER ID :");
        jLabel5.setToolTipText("");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setIconTextGap(5);
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 26));

        ManagerId.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        ManagerId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ManagerId.setPreferredSize(new java.awt.Dimension(80, 26));
        ManagerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerIdActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NAME:");
        jLabel7.setToolTipText("");
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setIconTextGap(5);
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 26));

        Name.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.setPreferredSize(new java.awt.Dimension(80, 26));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("GENDER :");
        jLabel8.setToolTipText("");
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setIconTextGap(5);
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 26));

        Gender.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        Gender.setAutoscrolls(true);
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PASSWORD :");
        jLabel9.setToolTipText("");
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setIconTextGap(5);
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 26));

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.setEchoChar('\u2022');
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
        });

        AddManager.setBackground(new java.awt.Color(204, 204, 204));
        AddManager.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        AddManager.setText("ADD MANAGER");
        AddManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddManagerMouseClicked(evt);
            }
        });
        AddManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddManagerActionPerformed(evt);
            }
        });

        EditManager.setBackground(new java.awt.Color(204, 204, 204));
        EditManager.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        EditManager.setText("EDIT MANAGER");
        EditManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditManagerMouseClicked(evt);
            }
        });
        EditManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditManagerActionPerformed(evt);
            }
        });

        DeleteManager.setBackground(new java.awt.Color(204, 204, 204));
        DeleteManager.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DeleteManager.setText("DELETE MANAGER");
        DeleteManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteManagerMouseClicked(evt);
            }
        });
        DeleteManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteManagerActionPerformed(evt);
            }
        });

        ManagersTable.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        ManagersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MANAGER ID", "NAME", "GENDER", "PASSWORD"
            }
        ));
        ManagersTable.setGridColor(new java.awt.Color(0, 0, 255));
        ManagersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManagersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ManagersTable);

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MANAGERS LIST");
        jLabel11.setToolTipText("");
        jLabel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.setIconTextGap(5);

        Logout.setBackground(new java.awt.Color(204, 204, 204));
        Logout.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        Logout.setText("LOGOUT");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddManager)
                                .addGap(43, 43, 43)
                                .addComponent(EditManager)
                                .addGap(148, 148, 148))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(DeleteManager))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Logout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddManager)
                            .addComponent(EditManager))
                        .addGap(18, 18, 18)
                        .addComponent(DeleteManager)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logout)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagerIdActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void AddManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddManagerActionPerformed

    private void EditManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditManagerActionPerformed

    private void DeleteManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteManagerActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked
    private boolean CheckUniqueManID(String s)
    {
        try{
            aon =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","dhanu","root123");
            PreparedStatement add = aon.prepareStatement("Select count(*) from Users where UserId=? and Role='MANAGER'");
            add.setString(1,String.valueOf(s));
            Rs=add.executeQuery();
            //aon.close();
            Rs.next();
            if(Rs.getInt(1)==0) 
            {
               // JOptionPane.showMessageDialog(this,"False");
                return true;
            }
            return false;
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        //.showMessageDialog(this,"Execp");
        return false;
    }
    private void AddManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddManagerMouseClicked
        // TODO add your handling code here:
         if(ManagerId.getText().isEmpty() || Name.getText().isEmpty() || Password.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Information is Missing");
       }
         else{
        try
        {
            Con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","dhanu","root123");
            PreparedStatement add = Con.prepareStatement("insert into Users values(?,?,?,?,?)");
            add.setString(1,String.valueOf(ManagerId.getText()));
            if(!CheckUniqueManID(ManagerId.getText().toString()))
            {
                JOptionPane.showMessageDialog(this,"Id Already Taken,Please Enter another ID");
                Con.close();
                return;
            }
            add.setString(2,String.valueOf(Name.getText()));
            add.setString(3,String.valueOf("MANAGER"));
            add.setString(4,String.valueOf(Gender.getSelectedItem().toString()));
            add.setString(5,String.valueOf(Password.getPassword()));
            int row=add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Added Successfully");  
            Con.close();
            SelectManager();
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         }
    }//GEN-LAST:event_AddManagerMouseClicked

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        // TODO add your handling code here:
        if(Password.echoCharIsSet())
        {
            Password.setEchoChar((char)0);
        }
    }//GEN-LAST:event_PasswordKeyPressed

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        // TODO add your handling code here:
        Password.setEchoChar('\u2022');
    }//GEN-LAST:event_PasswordKeyReleased

    private void ManagersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagersTableMouseClicked
        // TODO add your handling code here:
        try{
        DefaultTableModel model = (DefaultTableModel)ManagersTable.getModel();
        int Index=ManagersTable.getSelectedRow();
        ManagerId.setText(model.getValueAt(Index,0).toString());
        Name.setText(model.getValueAt(Index,1).toString());
        Gender.setSelectedItem(model.getValueAt(Index,2));
        Password.setText(model.getValueAt(Index,3).toString());
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ManagersTableMouseClicked

    private void EditManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditManagerMouseClicked
        // TODO add your handling code here:
        if(ManagerId.getText().isEmpty () || Name.getText().isEmpty() || Password.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this,"Information is Missing");
       }
         else{
        try
        {
            Con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","dhanu","root123");
            PreparedStatement add = Con.prepareStatement("update Users set Name=?,Gender=?,Password=? where UserId=?");
            add.setString(4,String.valueOf(ManagerId.getText()));
            if(CheckUniqueManID(ManagerId.getText().toString()))
            {
                JOptionPane.showMessageDialog(this,"ID doesn't Exist");
                Con.close();
                return;
            }
            add.setString(1,String.valueOf(Name.getText()));
            add.setString(2,String.valueOf(Gender.getSelectedItem().toString()));
            add.setString(3,String.valueOf(Password.getPassword()));
            int row=add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Edited Successfully");  
            Con.close();
            SelectManager();
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         }
    }//GEN-LAST:event_EditManagerMouseClicked

    private void DeleteManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteManagerMouseClicked
        // TODO add your handling code here:
        if(ManagerId.getText().isEmpty ())
       {
           JOptionPane.showMessageDialog(this,"ID is Missing");
       }
         else{
        try
        {
            Con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","dhanu","root123");
            PreparedStatement add = Con.prepareStatement("delete from Users where UserId=? and Role='MANAGER'");
            add.setString(1,String.valueOf(ManagerId.getText()));
            if(CheckUniqueManID(ManagerId.getText().toString()))
            {
                JOptionPane.showMessageDialog(this,"ID doesn't Exist");
                Con.close();
                return;
            }
            int row=add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Deleted Successfully");  
            Con.close();
            SelectManager();
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         }
    }//GEN-LAST:event_DeleteManagerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddManager;
    private javax.swing.JButton DeleteManager;
    private javax.swing.JButton EditManager;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField ManagerId;
    private javax.swing.JTable ManagersTable;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
